### PR TITLE
Fixed small path issues in bbswitch and bumblebee Pkgfiles

### PR DESCRIPTION
**Pull request by mhoush**
Couple of small issues with paths in the bbswitch and bumblebee ports (bumblebeed rc script and bbswitch module location).

### CODE REVIEW

**Comment by onodera-punpun** [comment]
Thanks!

**Comment by mhoush** [comment]
No problem, glad to help!

**Comment by rtlanceroad** [comment]
@mhoush just curious: how kernel release `uname -r`returns <kernel release> in bbswitch footprint ? :)

**Comment by mhoush** [comment]
I'm not sure I understand your question but what's happening is that pkgmk automatically replaces 'lib/modules/`uname -r`/' with 'lib/modules/<kernel-version>/' in the footprint. In bbswitch's case the module was in the wrong location so that replacement was not happening.

**Comment by rtlanceroad** [comment]
ok understood

**Pull request merged**
