### PR TITLE
Add: units

### PR DESCRIPTION
**Pull request by rmull**

### CODE REVIEW

**Comment by ix** [comment]
please fix your tabs before submitting

**Comment by rmull** [comment]
Sorry, is this better? I doubt I was supposed to squash into one commit and force push to my own repo, but that's what I did...

**Comment by Wildefyr** [comment]
I've fixed this for you, [merge this PR](https://github.com/rmull/crux-ports/pull/1) and add it to this pull request.

**Comment by rmull** [comment]
Thanks @Wildefyr, I see what was missing now, should be good to go.

**Comment by Wildefyr** [comment]
No problem! Feel free to use mkport in the cross repository.

**Comment by ix** [comment]
mkport doesn't fix this issue

I recommend adding the following lines to .vimrc/init.vim if you're using vim:

```viml
au BufNewFile,BufRead *Pkgfile set filetype=sh
au BufNewFile,BufRead *Pkgfile set noet
```

**Comment by Wildefyr** [comment]
No, but I changed it so if the output is indented, it uses tabs instead of spaces. nice vim-fu though.

**Pull request merged**
